{% raw -%}
name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/checkout@v1
      - name: Cache esy dependencies
        uses: actions/cache@v1
        id: cache
        with:
          path: _export
          key: ${{ runner.OS }}-build-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install esy
        run: npm install -g esy@latest

      - name: Import dependencies
        if: steps.cache.outputs.cache-hit == 'true'
        run: esy import-build _export/*

      - name: Install dependencies
        run: esy install

      - name: Build
        run: esy build

      - name: Check formatting
        run: |
          esy format
          if [ -n "$(git status --porcelain)" ]; then
            echo "There are differences:"
            git status --porcelain
            echo "----"
            echo ""
            echo 'Please run `esy format` locally to fix the issues.'
            exit 1
          fi

      - name: Run tests
        run: esy test
        
      - name: Export dependencies
        run: esy export-dependencies
{% endraw %}